"""Reusable constants for the kerjasama-agent application."""

# Message categories
CATEGORY_GREETING = "GREETING"
CATEGORY_AVAILABILITY = "AVAILABILITY"
CATEGORY_PRICING = "PRICING"
CATEGORY_OTHER = "OTHER"

# List of trained categories (OTHER is inferred from low confidence)
TRAINED_CATEGORIES = [CATEGORY_GREETING, CATEGORY_AVAILABILITY, CATEGORY_PRICING]

# All possible categories
ALL_CATEGORIES = [CATEGORY_GREETING, CATEGORY_AVAILABILITY, CATEGORY_PRICING, CATEGORY_OTHER]

# Classification confidence threshold
# If highest confidence is below this, return CATEGORY_OTHER
CONFIDENCE_THRESHOLD = 0.8

# User status constants
USER_STATUS_ONBOARDING = "ONBOARDING"
USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_SUSPENDED = "SUSPENDED"
USER_STATUS_ABANDONED = "ABANDONED"

# OAuth provider constants
OAUTH_PROVIDER_GOOGLE = "GOOGLE_CALENDAR"
OAUTH_PROVIDER_WHATSAPP = "WHATSAPP"

# Business AI voice constants
BUSINESS_AI_VOICE_FIRST_PERSON = "FIRST_PERSON"
BUSINESS_AI_VOICE_NAME = "BUSINESS_NAME"
BUSINESS_AI_VOICE_WE = "WE"

# Business workflow status constants
BUSINESS_WORKFLOW_STATUS_ACTIVE = "ACTIVE"
BUSINESS_WORKFLOW_STATUS_DISABLED = "INACTIVE"
